image: python:3.7

before_script:
  - apt-get update -qq && apt-get install -y -qq python3-pip shellcheck
  - which python3
  - python3 --version
  - python3 -m pip install -r requirements-dev.txt

pylint:
  script: pylint i3wsgroups scripts/i3-workspace-groups

pytype_py36:
  image: python:3.6
  script: pytype i3wsgroups

pytype_py37:
  script: pytype i3wsgroups

# NOTE: As of 2019-11-13, pytype doesn't support python 3.8 yet.
# pytype_py38:
#   image: python:3.8
#   script: pytype i3wsgroups

test_py36:
  image: python:3.6
  script: tox -e py36

test_py37:
  script: tox -e py37

test_py38:
  image: python:3.8
  script: tox -e py38

shellcheck:
  script: 
    - shellcheck scripts/i3-assign-workspace-to-group
    - shellcheck scripts/i3-focus-on-workspace
    - shellcheck scripts/i3-move-to-workspace
    - shellcheck scripts/i3-rename-workspace
    - shellcheck scripts/i3-switch-active-workspace-group

setup_develop:
  script: python3 setup.py develop
