name: i3_workspace_groups
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # - pylint
  # - yapf
  # - virtualenv
  # - tox
  # - tox-conda
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
